version: 2
workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - checks:
          filters:
            tags:
              only: /.*/
      - build-and-release:
          requires: [test, checks]
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
jobs:
  test:
    docker:
      - image: darthjee/circleci_timeshift-base:0.0.1
        environment:
          TIMESHIFT_MYSQL_HOST: mysql
          TIMESHIFT_MYSQL_PORT: 3306
          TIMESHIFT_MYSQL_USER: timeshift
          TIMESHIFT_MYSQL_NAME: timeshift
          TIMESHIFT_MYSQL_PASSWORD: timeshift
          TIMESHIFT_PASSWORD_SALT: abcd
      - image: circleci/mysql:5.7
        name: mysql
        environment:
          MYSQL_DATABASE: timeshift_test
          MYSQL_USER: timeshift
          MYSQL_PASSWORD: timeshift
    steps:
      - checkout
      - run:
          name: Set folder
          command: cp source/* source/.??* ./ -r; rm source -rf
      - run:
          name: Prepare Coverage Test Report
          command: cc-test-reporter before-build
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Bower Install
          command: bundle exec rake bower:install
      - run:
          name: Wait for database
          command: scripts/wait_for_db.sh
      - run:
          name: Migrate
          command: RAILS_ENV=test bundle exec rake db:schema:load
      - run:
          name: RSpec
          command: bundle exec rspec
      - run:
          name: Coverage Test Report
          command: cc-test-reporter after-build --exit-code $?

  checks:
    docker:
      - image: darthjee/circleci_timeshift-base:0.0.1
        environment:
          TIMESHIFT_MYSQL_HOST: mysql
          TIMESHIFT_MYSQL_PORT: 3306
          TIMESHIFT_MYSQL_USER: timeshift
          TIMESHIFT_MYSQL_NAME: timeshift
          TIMESHIFT_MYSQL_PASSWORD: timeshift
          TIMESHIFT_PASSWORD_SALT: abcd
      - image: circleci/mysql:5.7
        name: mysql
        environment:
          MYSQL_DATABASE: timeshift_test
          MYSQL_USER: timeshift
          MYSQL_PASSWORD: timeshift
    steps:
      - checkout
      - run:
          name: Set folder
          command: cp source/* source/.??* ./ -r; rm source -rf
      - run:
          name: Bundle Install
          command: bundle install
      - run:
          name: Rubocop
          command: rubocop
  build-and-release:
    machine: true
    steps:
      - checkout
      - run:
          name: Trigger Deploy
          command: scripts/deploy.sh deploy
