# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52b99f3811684a1396b221c0809230ff618e9311bdd60a93a705337b4de06ab1a5ed68b9e57c563dbf294bb61067439c46e37f7c62b36fbc8cbdc8928f6c3d2a

test:
  secret_key_base: e6d268eb2ca1af57faef3e635d8b975e7754a02a6f58bf03e3ca9b025c3ebba16495713721fae687b17bf54c144f571dd60dd29e6ed93fafc112fba8562b3242

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
