# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.0'

gem 'bundler', '2.3.25'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '7.0.4.3'

# Use pg as the database for Active Record
gem 'mysql2'
# Use Puma as the app server
gem 'puma', '~> 4.3.8'
# Use SCSS for stylesheets
gem 'sass-rails', '6.0.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '4.2.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'coffee-rails', '4.2.2'
gem 'jbuilder', '~> 2.5'
gem 'jquery-rails', '4.3.1'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

gem 'arstotzka',    '~> 1.6.2'
gem 'azeroth',      '>= 1.0.0'
gem 'bower-rails',  '~> 0.12.0'
gem 'newrelic_rpm', '~> 8.12.0'
gem 'nokogiri',     '1.13.10'
gem 'rack',         '~> 2.x'
gem 'rake',         '13.0.6'
gem 'sinclair',     '~> 2.0.0'
gem 'sprockets',    '~> 3.x'
gem 'tarquinn',     '~> 0.2.0'
gem 'turbolinks',   '5.2.1'
gem 'tzinfo-data'

gem 'darthjee-active_ext', '>= 1.3.2'
gem 'darthjee-core_ext', '>= 2.0.0'
gem 'magicka', '~> 1.0.0'

gem 'mini_magick'
gem 'recursive-open-struct'
gem 'rollbar'
gem 'rqrcode_png'
gem 'sentry-raven'

group :development do
  # Access an interactive console on exception pages
  # or by calling 'console' anywhere in the code.
  gem 'listen',                '3.2.1'
  gem 'spring',                '4.1.1'
  gem 'spring-watcher-listen'
  gem 'web-console',           '3.7.0'

  gem 'pry',                   '0.14.1'
  gem 'pry-nav',               '1.0.0'
  gem 'pry-rails',             '0.3.9'
  gem 'reek',                  '6.0.3'
  gem 'rspec',                 '3.11.0'
  gem 'rspec-core',            '3.11.0'
  gem 'rspec-expectations',    '3.11.0'
  gem 'rspec-mocks',           '3.11.1'
  gem 'rspec-rails',           '5.1.2'
  gem 'rspec-support',         '3.11.0'
  gem 'rubocop',               '0.80.1'
  gem 'rubocop-rspec',         '1.38.1'
  gem 'rubycritic',            '4.7.0'
  gem 'shoulda-matchers',      '4.3.0'
  gem 'simplecov',             '0.21.2'
  gem 'yard',                  '0.9.27'
  gem 'yardstick',             '0.9.9'
end

group :development, :test do
  gem 'factory_bot',  '6.2.1'
  gem 'timecop',      '0.9.1'
  gem 'zonebie',      '0.6.1'

  gem 'rails-controller-testing', '1.0.5'
end

group :test do
  gem 'webmock', '3.8.2'

  gem 'database_cleaner',          '1.8.3'
  gem 'rspec-collection_matchers', '1.2.0'
end
