# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.0'
gem 'importmap-rails'
gem 'jbuilder'
gem 'mysql2'
gem 'puma', '~> 5.0'
gem 'rails', '~> 7.0.4', '>= 7.0.4.3'
gem 'sprockets-rails'
gem 'stimulus-rails'
gem 'turbo-rails'

gem 'bootsnap', require: false
gem 'sassc-rails', '>= 2.1.2'
gem 'tzinfo-data'
gem 'uglifier', '4.2.0'
gem 'rack', '>= 2.2.6.3'
gem 'globalid', '>= 1.1.0'

gem 'azeroth',      '>= 1.0.0'
gem 'bower-rails',  '~> 0.12.0'
gem 'darthjee-active_ext', '>= 1.3.2'
gem 'darthjee-core_ext', '>= 2.0.0'
gem 'magicka', '~> 1.1.0'
gem 'nokogiri', '1.14.4'
gem 'sinclair', '~> 2.0.1'
gem 'tarquinn', '~> 0.2.0'

group :development, :test do
  gem 'factory_bot',        '6.2.1'
  gem 'pry',                '>= 0.14.2'
  gem 'pry-nav',            '>= 1.0.0'
  gem 'pry-rails',          '>= 0.3.9'
  gem 'reek',               '>= 6.1.4'
  gem 'rspec',              '>= 3.12.0'
  gem 'rspec-core',         '3.12.2'
  gem 'rspec-expectations', '3.12.3'
  gem 'rspec-mocks',        '3.12.5'
  gem 'rspec-rails',        '6.0.2'
  gem 'rspec-support',      '3.12.0'
  gem 'rubocop',            '1.51.0'
  gem 'rubocop-rspec',      '2.22.0'
  gem 'rubycritic',         '4.8.0'
  gem 'shoulda-matchers',   '5.3.0'
  gem 'simplecov',          '0.22.0'
  gem 'timecop',            '0.9.6'
  gem 'yard',               '0.9.34'
  gem 'yardstick',          '0.9.9'
  gem 'zonebie',            '0.6.1'

  gem 'rails-controller-testing', '1.0.5'
end

group :development do
  gem 'web-console', '4.2.0'
end

group :test do
  gem 'database_cleaner', '2.0.2'
  gem 'webmock',          '3.18.1'

  gem 'rspec-collection_matchers', '1.2.0'
end
